"""Reporting — render an Assessment to Markdown, JSON, and SARIF.

Reporting is explicit and multi-audience:
  * Markdown  -> humans (PR comments, audit evidence)
  * JSON      -> machines (dashboards, data lake, trend analysis)
  * SARIF     -> GitHub code scanning / security tab (one result per failure)
"""
from __future__ import annotations

import json
from typing import Any

from sre_governance.audit import provenance
from sre_governance.engine import FAIL, NA, PASS, Assessment

_STATUS_ICON = {PASS: "✅", FAIL: "❌", NA: "➖"}
_SEV_ICON = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "⚪"}


def render_markdown(assessment: Assessment, profile_display: str, catalog_version: str) -> str:
    s = assessment.summary
    gate = assessment.gate
    gate_badge = "🟢 COMPLIANT" if gate.compliant else "🔴 NON-COMPLIANT"
    lines: list[str] = []
    lines.append(f"# SRE Governance Report — {profile_display}")
    lines.append("")
    lines.append(f"**Repository:** `{assessment.repo}`  ")
    lines.append(f"**Profile:** `{assessment.profile}`  ")
    lines.append(f"**Catalog version:** `{catalog_version}`  ")
    lines.append(f"**Compliance score:** **{assessment.score}%**  ")
    lines.append(f"**Policy gate:** {gate_badge} (enforcement: `{gate.enforcement}`)")
    lines.append("")
    if gate.reasons:
        lines.append("> **Gate failure reasons:**")
        for r in gate.reasons:
            lines.append(f"> - {r}")
        lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Controls evaluated | {s['total_controls']} |")
    lines.append(f"| Passed | {s['passed']} |")
    lines.append(f"| Failed | {s['failed']} |")
    lines.append(f"| Not applicable | {s['not_applicable']} |")
    lines.append(f"| Blocking (mandatory) failures | {s['blocking_failures']} |")
    fb = s["failures_by_severity"]
    lines.append(f"| Failures by severity | 🔴 {fb['critical']} · 🟠 {fb['high']} · 🟡 {fb['medium']} · ⚪ {fb['low']} |")
    lines.append("")

    failures = [r for r in assessment.results if r.status == FAIL]
    if failures:
        lines.append("## ❌ Failed controls (remediation required)")
        lines.append("")
        lines.append("| Control | Sev | Applicability | Finding | Remediation |")
        lines.append("|---|---|---|---|---|")
        for r in sorted(failures, key=lambda x: _sev_rank(x.severity)):
            lines.append(
                f"| `{r.control_id}` {r.title} | {_SEV_ICON[r.severity]} {r.severity} "
                f"| {r.applicability} | {r.reason} | {r.remediation} |"
            )
        lines.append("")

    lines.append("## All controls")
    lines.append("")
    lines.append("| Status | Control | Category | Sev | Frameworks |")
    lines.append("|---|---|---|---|---|")
    for r in assessment.results:
        frameworks = ", ".join(sorted(r.mappings.keys())) if r.mappings else "—"
        lines.append(
            f"| {_STATUS_ICON[r.status]} | `{r.control_id}` {r.title} "
            f"| {r.category} | {_SEV_ICON[r.severity]} | {frameworks} |"
        )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "_Generated by the SRE Governance Agent. Pass/fail is computed by the "
        "deterministic policy engine; AI assists only with interpretation and "
        "remediation. See `audit.jsonl` for the signed action trail._"
    )
    lines.append("")
    return "\n".join(lines)


def render_json(assessment: Assessment, catalog_version: str) -> str:
    payload: dict[str, Any] = {
        "provenance": provenance(assessment.profile, catalog_version, assessment.score),
        "repo": assessment.repo,
        "profile": assessment.profile,
        "score": assessment.score,
        "gate": {
            "compliant": assessment.gate.compliant,
            "enforcement": assessment.gate.enforcement,
            "should_fail_pipeline": assessment.gate.should_fail_pipeline,
            "reasons": assessment.gate.reasons,
        },
        "summary": assessment.summary,
        "results": [
            {
                "control_id": r.control_id,
                "title": r.title,
                "category": r.category,
                "severity": r.severity,
                "status": r.status,
                "applicability": r.applicability,
                "reason": r.reason,
                "remediation": r.remediation,
                "mappings": r.mappings,
            }
            for r in assessment.results
        ],
    }
    return json.dumps(payload, indent=2)


def render_sarif(assessment: Assessment) -> str:
    """Minimal SARIF 2.1.0 so failures surface in the GitHub Security tab."""
    sarif_level = {"critical": "error", "high": "error", "medium": "warning", "low": "note"}
    rules = []
    results = []
    seen_rules: set[str] = set()
    for r in assessment.results:
        if r.control_id not in seen_rules:
            rules.append({
                "id": r.control_id,
                "name": r.title,
                "shortDescription": {"text": r.title},
                "defaultConfiguration": {"level": sarif_level.get(r.severity, "warning")},
                "properties": {"category": r.category, "severity": r.severity},
            })
            seen_rules.add(r.control_id)
        if r.status == FAIL:
            results.append({
                "ruleId": r.control_id,
                "level": sarif_level.get(r.severity, "warning"),
                "message": {"text": f"{r.title}: {r.reason}. Remediation: {r.remediation}"},
            })
    sarif = {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {"driver": {
                "name": "SRE-Governance-Agent",
                "informationUri": "https://github.com/rradenheimer/sre-governance-agent",
                "version": "1.0.0",
                "rules": rules,
            }},
            "results": results,
        }],
    }
    return json.dumps(sarif, indent=2)


def _sev_rank(sev: str) -> int:
    return {"critical": 0, "high": 1, "medium": 2, "low": 3}.get(sev, 9)
